{
package anytime
}

Input <- locRange:LocatedRange .* EOF {
    return locRange, nil
}

LocatedRange <- rangefn:Range {
    return LocatedRange{
        RangeFn: rangefn.(RangeFunc),
        Pos:   c.pos.offset,
        Text:  c.text,
    }, nil
}

Range <- "now" {
    return RangeFunc(func(ref time.Time, dir Direction) Range {
        return Range{
            start: ref,
            Duration: time.Second,
        }
    }), nil
}

EOF <- !.
